-- =============================================================================
-- Seed data for Observatoire 360
-- Run via: wrangler d1 execute observatoire360-db --local --file=src/db/seed.sql
--
-- NOTE on password hashes:
--   Passwords are stored as pbkdf2:<iterations>:salt_base64:hash_base64
--   The hashes below were pre-computed using the app's hashPassword() function.
--   For production use, always generate hashes via the app rather than hardcoding.
--
--   To generate real hashes for seed accounts:
--     1. Start the dev server: pnpm dev
--     2. Use the admin interface or POST /api/auth/forgot-password to reset passwords.
--   Or run the TypeScript seed script (see docs/seeding.md).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Municipalities
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO municipalities (id, name, code, region, bounds, created_at) VALUES
(
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    'Sherbrooke',
    'SHE',
    'Estrie',
    '{"north":45.5200,"south":45.3300,"east":-71.7800,"west":-72.0500}',
    1700000000
),
(
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    'Magog',
    'MAG',
    'Estrie',
    '{"north":45.3200,"south":45.2400,"east":-72.0800,"west":-72.2200}',
    1700000001
),
(
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    'Lac-Mégantic',
    'LAC',
    'Estrie',
    '{"north":45.6200,"south":45.5400,"east":-70.8500,"west":-71.0200}',
    1700000002
);

-- ---------------------------------------------------------------------------
-- Users
-- Note: password_hash values below use a placeholder format.
-- Replace with real PBKDF2 hashes generated by the app before production use.
-- The value below is a valid-format placeholder — regenerate before deploying.
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO users (id, municipality_id, email, password_hash, name, role, is_active, created_at, updated_at) VALUES
(
    '01GW1FKJPQR2T3V4W5X6YUSER1',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    'demo@observatoire360.com',
    'REDACTED_PBKDF2_HASH',
    'Demo Admin',
    'manager',
    1,
    1700000100,
    1700000100
),
(
    '01GW1FKJPQR2T3V4W5X6YUSER2',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    'admin.sherbrooke@obs360.com',
    'REDACTED_PBKDF2_HASH',
    'Admin Sherbrooke',
    'manager',
    1,
    1700000200,
    1700000200
),
(
    '01GW1FKJPQR2T3V4W5X6YUSER3',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    'inspector@obs360.com',
    'REDACTED_PBKDF2_HASH',
    'Jean Inspecteur',
    'inspector',
    1,
    1700000300,
    1700000300
),
(
    '01GW1FKJPQR2T3V4W5X6YUSER4',
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    'analyst@obs360.com',
    'REDACTED_PBKDF2_HASH',
    'Marie Analyste',
    'analyst',
    1,
    1700000400,
    1700000400
),
(
    '01GW1FKJPQR2T3V4W5X6YUSER5',
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    'readonly@obs360.com',
    'REDACTED_PBKDF2_HASH',
    'Pierre Lecture',
    'readonly',
    1,
    1700000500,
    1700000500
);

-- ---------------------------------------------------------------------------
-- Alerts — 15 across 3 municipalities, varied risk/status/type
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO alerts
    (id, municipality_id, latitude, longitude, risk_level, risk_score, status, type,
     detected_area, authorized_area, zone, has_permit, address, detected_at, images, created_at)
VALUES
-- Sherbrooke (5 alerts)
(
    '01GW1ALERT000000000001',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    45.4042, -71.8929, 'high', 87, 'infraction_confirmee', 'construction',
    245.0, 0.0, 'Zone résidentielle faible densité', 0,
    '245 Rue King Est, Sherbrooke', 1698000000, '[]', 1698000000
),
(
    '01GW1ALERT000000000002',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    45.4102, -71.9012, 'medium', 55, 'a_inspecter', 'extension',
    85.0, 60.0, 'Zone commerciale', 1,
    '1200 Boul Portland, Sherbrooke', 1699000000, '[]', 1699000000
),
(
    '01GW1ALERT000000000003',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    45.3980, -71.8855, 'low', 22, 'cloturee', 'piscine',
    28.0, 30.0, 'Zone résidentielle', 1,
    '88 Rue Wellington Nord, Sherbrooke', 1697000000, '[]', 1697000000
),
(
    '01GW1ALERT000000000004',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    45.4200, -71.8750, 'high', 92, 'a_analyser', 'construction',
    380.0, NULL, 'Zone agricole', 0,
    '550 Chemin des Cantons, Sherbrooke', 1700500000, '[]', 1700500000
),
(
    '01GW1ALERT000000000005',
    '01GW1FKJPQR2T3V4W5X6Y7Z8A9',
    45.3910, -71.9180, 'medium', 61, 'en_cours', 'annexe',
    42.0, NULL, 'Zone résidentielle mixte', 0,
    '77 Rue Bowen Sud, Sherbrooke', 1699500000, '[]', 1699500000
),
-- Magog (5 alerts)
(
    '01GW1ALERT000000000006',
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    45.2611, -72.1478, 'high', 78, 'a_inspecter', 'construction',
    190.0, 0.0, 'Zone résidentielle basse densité', 0,
    '115 Rue Principale Ouest, Magog', 1699200000, '[]', 1699200000
),
(
    '01GW1ALERT000000000007',
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    45.2688, -72.1390, 'low', 18, 'cloturee', 'piscine',
    24.0, 24.0, 'Zone résidentielle', 1,
    '42 Rue Saint-Patrice Est, Magog', 1697500000, '[]', 1697500000
),
(
    '01GW1ALERT000000000008',
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    45.2730, -72.1510, 'medium', 48, 'a_analyser', 'extension',
    66.0, 40.0, 'Zone commerciale riveraine', 0,
    '230 Rue Merry Nord, Magog', 1700100000, '[]', 1700100000
),
(
    '01GW1ALERT000000000009',
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    45.2580, -72.1600, 'high', 83, 'infraction_confirmee', 'construction',
    310.0, NULL, 'Zone agricole protégée', 0,
    '890 Chemin du Roy, Magog', 1698500000, '[]', 1698500000
),
(
    '01GW1ALERT000000000010',
    '01GW1FKJPQR2T3V4W5X6Y7Z8B0',
    45.2644, -72.1445, 'medium', 53, 'en_cours', 'annexe',
    35.0, NULL, 'Zone résidentielle', 0,
    '18 Rue de la Rivière, Magog', 1699800000, '[]', 1699800000
),
-- Lac-Mégantic (5 alerts)
(
    '01GW1ALERT000000000011',
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    45.5774, -70.8831, 'medium', 44, 'a_analyser', 'construction',
    120.0, NULL, 'Zone résidentielle', 0,
    '3500 Rue Laval, Lac-Mégantic', 1700300000, '[]', 1700300000
),
(
    '01GW1ALERT000000000012',
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    45.5810, -70.8780, 'low', 15, 'cloturee', 'piscine',
    20.0, 25.0, 'Zone résidentielle', 1,
    '12 Rue des Érables, Lac-Mégantic', 1697200000, '[]', 1697200000
),
(
    '01GW1ALERT000000000013',
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    45.5740, -70.8900, 'high', 90, 'infraction_confirmee', 'construction',
    420.0, 0.0, 'Zone riveraine protégée', 0,
    '99 Rue du Lac, Lac-Mégantic', 1698800000, '[]', 1698800000
),
(
    '01GW1ALERT000000000014',
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    45.5760, -70.8840, 'medium', 58, 'a_inspecter', 'extension',
    75.0, 50.0, 'Zone résidentielle mixte', 0,
    '456 Boul des Vétérans, Lac-Mégantic', 1699600000, '[]', 1699600000
),
(
    '01GW1ALERT000000000015',
    '01GW1FKJPQR2T3V4W5X6Y7Z8C1',
    45.5720, -70.8960, 'low', 30, 'en_cours', 'annexe',
    38.0, NULL, 'Zone agricole', 0,
    '27 Rang des Sommets, Lac-Mégantic', 1700000000, '[]', 1700000000
);

-- ---------------------------------------------------------------------------
-- Inspections — 5 records
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO inspections
    (id, alert_id, inspector_id, scheduled_date, status, notes, created_at, updated_at)
VALUES
(
    '01GW1INSPECT00000000001',
    '01GW1ALERT000000000001',
    '01GW1FKJPQR2T3V4W5X6YUSER3',
    '2024-01-15', 'completed',
    'Inspection réalisée. Construction sans permis confirmée. Dossier transmis au contentieux.',
    1704672000, 1705449600
),
(
    '01GW1INSPECT00000000002',
    '01GW1ALERT000000000005',
    '01GW1FKJPQR2T3V4W5X6YUSER3',
    '2024-03-10', 'planned',
    'Première visite à planifier avec le propriétaire.',
    1708300800, 1708300800
),
(
    '01GW1INSPECT00000000003',
    '01GW1ALERT000000000006',
    '01GW1FKJPQR2T3V4W5X6YUSER3',
    '2024-02-20', 'in_progress',
    'Inspection en cours — documents demandés au propriétaire.',
    1707350400, 1708000000
),
(
    '01GW1INSPECT00000000004',
    '01GW1ALERT000000000009',
    '01GW1FKJPQR2T3V4W5X6YUSER3',
    '2024-01-28', 'completed',
    'Infraction confirmée. Mise en demeure envoyée.',
    1706054400, 1706572800
),
(
    '01GW1INSPECT00000000005',
    '01GW1ALERT000000000013',
    '01GW1FKJPQR2T3V4W5X6YUSER3',
    '2024-04-05', 'planned',
    NULL,
    1709596800, 1709596800
);
